# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MGAwsSnsManagerSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MGAwsSnsManagerSwift
  pod 'AWSCore', '~> 2.6.31'
  pod 'AWSSNS', '~> 2.6.31'
  pod 'AWSCognito', '~> 2.6.31'

end
